language: python
cache: pip
python:
  - "3.6"

before_install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install mkdocs
  - pip install pygments
  - pip install mkdocs-material
  - pip install pymdown-extensions
script:
  - py.test
after_success:
  - COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN} coveralls
  - mkdocs build

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    local_dir: site
    edge: true
    on:
      branch: master
  provider: pypi
    user: danielecook
    password: $PYPI
    on:
      branch: master