site_name: IEX-API-Python
theme:
  name: 'readthedocs'

pages:
  - Home: index.md
  - Getting Started: getting_started.md
  - Stock: stocks.md
  - Batch: batch.md
  - Reference Data: reference_data.md
  - IEX Stats: iex_stats.md
  - Markets: market.md

repo_url: https://github.com/danielecook/iex-api-python
markdown_extensions:
    - admonition
    - codehilite
    - toc:
        permalink: True
    - fenced_code
    - sane_lists
    - footnotes
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

extra_css: ['https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css', static/style.css]
extra_javascript: [static/docs_js.js]

plugins:
    - search

google_analytics:
  - 'UA-39176354-4'
  - 'auto'
