site_name: IEX-API-Python
theme: 
  name: 'material'
  palette:
    primary: 'Amber'
    accent: 'Light Blue'
  logo: 'iex_logo.png'
  feature:
    tabs: true

pages:
  - Home: index.md
  - Stock: stocks.md
  - Batch: batch.md
  - Reference Data: reference_data.md

repo_url: https://github.com/danielecook/iex-api-python
site_favicon: favicon.png
markdown_extensions:
    - admonition
    - codehilite
    - toc:
        permalink: True
    - fenced_code
    - sane_lists
    - fontawesome_markdown

extra_javascript: [static/docs_js.js]

plugins:
    - search

google_analytics:
  - 'UA-39176354-4'
  - 'auto'