site_name: IEX-API-Python
theme: 
  name: 'material'
  palette:
    primary: 'Amber'
    accent: 'Light Blue'
  logo: 'iex_logo.png'
  favicon: 'iex_logo.png'
  feature:
    tabs: true

pages:
  - Home: index.md
  - Stock: stocks.md
  - Batch: batch.md
  - Market: market.md
  - Reference Data: reference_data.md

repo_url: https://github.com/danielecook/iex-api-python
markdown_extensions:
    - admonition
    - codehilite
    - toc:
        permalink: True
    - fenced_code
    - sane_lists
    - footnotes
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

extra_css: [static/style.css]
extra_javascript: [static/docs_js.js]

plugins:
    - search

google_analytics:
  - 'UA-39176354-4'
  - 'auto'